language: objective-c

before_install:
    - gem install cocoapods
    - brew update
    - brew uninstall xctool && brew install xctool

script:
    - xctool -workspace crypto-sdk.xcworkspace -scheme crypto-sdk -sdk iphonesimulator -configuration Debug test
    - pod spec lint AeroGear-Crypto.podspec --verbose

notifications:
  irc: "irc.freenode.org#aerogear"
  
branches:
  only:
    - master
    
