language: objective-c

before_install:
    - brew unlink xctool
    - brew update
    - brew install xctool
script:
    - xctool clean build test ONLY_ACTIVE_ARCH=NO

notifications:
  irc: "irc.freenode.org#aerogear"
  
branches:
  only:
    - master
