language: objective-c

before_install:
    - gem install cocoapods -v 0.33.1 --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty -v 0.1.6 --no-rdoc --no-ri --no-document --quiet

script:
    - set -o pipefail && xcodebuild -workspace crypto-sdk.xcworkspace -scheme crypto-sdk -sdk iphonesimulator -configuration Release clean test | xcpretty -c
    - pod spec lint AeroGear-Crypto.podspec --verbose

notifications:
  irc: "irc.freenode.org#aerogear"
  
branches:
  only:
    - master
    
