language: objective-c

before_install:
    - brew unlink xctool
    - brew update
    - brew install xctool
script:
    - xctool -workspace crypto-sdk.xcworkspace -scheme crypto-sdk
    - pod spec lint AeroGear-Crypto.podspec --verbose

notifications:
  irc: "irc.freenode.org#aerogear"
  
branches:
  only:
    - master
